services:
  - type: web
    name: payout-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./artifacts/telegram-bot
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: "7908632313"
      - key: PROFIT_CHAT_ID
        value: "-1003413725881"
      - key: PROFIT_THREAD_ID
        value: "9"
    healthCheckPath: /health
